// <auto-generated />
using LogHubWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LogHubWebAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180725191853_addedBandwidth")]
    partial class addedBandwidth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LogHubWebAPI.Models.Organization", b =>
                {
                    b.Property<string>("OrganizationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OrganizationName");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("LogHubWebAPI.Models.OverallBandwidth", b =>
                {
                    b.Property<string>("OverallBandwidthId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bandwith");

                    b.Property<bool>("Included");

                    b.Property<DateTime>("Time");

                    b.HasKey("OverallBandwidthId");

                    b.ToTable("OverallBandwidth");
                });

            modelBuilder.Entity("LogHubWebAPI.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BandwidthSetting");

                    b.Property<string>("Email");

                    b.Property<string>("OrganizationId");

                    b.Property<string>("Password");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
